### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by ndench** [AlaaSarhan/oauth2-docusign#10]
Is there anything preventing a change from `"php": "^5.6|^7.0"` to `"php": "^5.6|^7.0|^8.0"`? If there are other changes required, happy to submit a PR if you let me know what needs to be done.

**Comment by AlaaSarhan** [comment]
On it @ndench!

**Comment by AlaaSarhan** [comment]
@ndench Release in https://github.com/AlaaSarhan/oauth2-docusign/releases/tag/v2.0.0
